# Generated by Django 5.1.3 on 2024-11-30 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0002_leaverequest_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tracking.customuser"
            ),
        ),
    ]
